# Rustfmt configuration for nightly Rust
# Includes advanced options available in nightly

# Basic formatting
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# Imports
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Code structure
reorder_imports = true
reorder_modules = true
match_block_trailing_comma = true
trailing_semicolon = true
use_field_init_shorthand = true

# Comments
wrap_comments = true
comment_width = 100
normalize_comments = true

# Misc
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true

# Spacing and brackets
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
binop_separator = "Front"
combine_control_expr = true
overflow_delimited_expr = true
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
