[package]
name = "skyvault"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "skyvault"
path = "bin/main.rs"

[lints.clippy]
unwrap_used = "deny"

[dependencies]
tonic = "0.13"
tonic-health = "0.13"
tonic-reflection = "0.13"
tokio = { version = "1", features = ["full"] }
prost = "0.13"
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
async-trait = "0.1"
thiserror = "2.0"
anyhow = "1.0"
structopt = "0.3"
futures = "0.3"
byteorder = "1.5"
aws-config = "1.6"
aws-sdk-dynamodb = "1.71"
aws-sdk-s3 = "1.82"
aws-smithy-runtime-api = "1.8.0"
ulid = "1.2.1"
async-stream = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+1"] }
k8s-openapi = { version = "0.24.0", features = ["v1_32"] }
hostname = "0.4"
kube = "0.99"
rustls = "0.23"

[build-dependencies]
tonic-build = "0.13"

[dev-dependencies]
testcontainers-modules = { version = "0.11.6", features = ["dynamodb"] }
