[package]
name = "skyvault"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "skyvault"
path = "bin/main.rs"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"

[dependencies]
tonic = "0.13"
tonic-health = "0.13"
tokio = { version = "1", features = ["full"] }
prost = "0.13"
clap = { version = "4.4", features = ["derive"] }
slog = "2.7"
slog-term = "2.9"
slog-async = "2.7"
slog-scope = "4.4"
slog-stdlog = "4.1"
tokio-retry = "0.3"
async-trait = "0.1"
thiserror = "2.0"
anyhow = "1.0"
structopt = "0.3"
rusqlite = { version = "0.29", features = ["bundled"] }
futures = "0.3"

[build-dependencies]
tonic-build = "0.13"

[dev-dependencies]
tempfile = "3.19.1"
