# Helm Chart Configuration for local development

# Common configuration for all Skyvault instances
common:
  image:
    id: localhost/skyvault:dev
    pullPolicy: IfNotPresent

  env:
    # S3
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: minioadmin
    AWS_SECRET_ACCESS_KEY: minioadmin
    AWS_ENDPOINT_URL_S3: http://skyvault-minio:9000

    # Postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: skyvault
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: skyvault-postgres

    # Rust
    RUST_BACKTRACE: 1

deployments:
  dev:
    enabled: false
    instanceName: "dev"
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    service:
      type: NodePort
      port: 50051
      nodePort: 30051
    # Instance-specific environment variables
    env:
      RUST_LOG: "skyvault=debug"

# Service account configuration
serviceAccount:
  create: true
  annotations: {}

# Values for the minio service
minio:
  enabled: true
  image:
    repository: docker.io/minio/minio
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 9000
    type: ClusterIP

# Values for the PostgreSQL service
postgres:
  enabled: true
  image:
    repository: docker.io/postgres
    tag: "12"
    pullPolicy: IfNotPresent
  service:
    port: 5432
    type: ClusterIP