# Default values for skyvault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common configuration for all SkyVault instances
common:
  image:
    repository: localhost/skyvault
    pullPolicy: Never
    tag: dev
  
  # Common environment variables for all deployments
  env:
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: minioadmin
    AWS_SECRET_ACCESS_KEY: minioadmin

# Multiple deployment instances configuration
deployments:
  # First instance - you can have multiple of these with different keys
  instance1:
    enabled: true
    instanceName: "primary"
    replicaCount: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    service:
      type: ClusterIP
      port: 50051
    # Instance-specific environment variables
    env:
      LOG_LEVEL: "info"
      
  # Second instance example with different config
  instance2:
    enabled: true
    instanceName: "secondary"
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    service:
      type: ClusterIP
      port: 50052
    env:
      LOG_LEVEL: "debug"

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

# Values for the dynamodb-local service
dynamodb:
  enabled: true
  image:
    repository: docker.io/amazon/dynamodb-local # Use fully qualified name
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8000

# Values for the minio service
minio:
  enabled: true
  image:
    repository: docker.io/minio/minio
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 9000
  # MinIO required environment variables
  env:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
 
