apiVersion: v1
kind: Secret
metadata:
  name: skyvault-aws-credentials
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.common.secrets.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.common.secrets.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
