apiVersion: v1
kind: Secret
metadata:
  name: skyvault-postgres-password
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.common.env.POSTGRES_PASSWORD | b64enc | quote }}