# DynamoDB Local Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skyvault.fullname" . }}-dynamodb
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "skyvault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dynamodb
  template:
    metadata:
      labels:
        {{- include "skyvault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dynamodb
    spec:
      containers:
        - name: dynamodb-local
          image: "{{ .Values.dynamodb.image.repository }}:{{ .Values.dynamodb.image.tag }}"
          imagePullPolicy: {{ .Values.dynamodb.image.pullPolicy }}
          ports:
            - name: dynamodb
              containerPort: {{ .Values.dynamodb.service.port }}
              protocol: TCP
          args: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "."] 