{{- range $jobType, $config := .Values.jobDynamicConfigs }}
---
# Dynamic ConfigMap for {{ $jobType }} jobs
apiVersion: v1
kind: ConfigMap
metadata:
  name: skyvault-dynamic-config-{{ $jobType }}
  labels:
    {{- include "skyvault.labels" $ | nindent 4 }}
    batch.skyvault.io/type: {{ $jobType }}
data:
  {{- if $config.writerConcurrentUploads }}
  writer_concurrent_uploads: {{ $config.writerConcurrentUploads | quote }}
  {{- end }}
  {{- if $config.orchestratorJobRetryLimit }}
  orchestrator_job_retry_limit: {{ $config.orchestratorJobRetryLimit | quote }}
  {{- end }}
{{- end }} 