{{- if .Values.minio.enabled }}
# MinIO Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyvault-minio
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "skyvault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "skyvault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          ports:
            - name: minio-api
              containerPort: {{ .Values.minio.service.port }}
              protocol: TCP
            # MinIO Console port
            - name: minio-console
              containerPort: 9001
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: skyvault-aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skyvault-aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          args:
            - server
            - /data # MinIO still needs a path, even without PVC
            - --console-address
            - :9001 
{{- end }}