{{- if .Values.postgres.enabled }}
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyvault-postgres
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "skyvault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "skyvault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{ .Values.common.env.SKYVAULT_POSTGRES_USER | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.common.env.SKYVAULT_POSTGRES_DB | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skyvault-postgres-password
                  key: POSTGRES_PASSWORD
{{- end }}