apiVersion: v1
kind: ConfigMap
metadata:
  name: skyvault-reset-db-job-spec
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
data:
  job.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: skyvault-reset-db-
      labels:
        {{- include "skyvault.labels" . | nindent 8 }}
        app.kubernetes.io/component: reset-db
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            {{- include "skyvault.labels" . | nindent 12 }}
            app.kubernetes.io/component: reset-db
        spec:
          restartPolicy: Never
          serviceAccountName: skyvault-serviceaccount
          containers:
          - name: reset-cluster
            image: {{ .Values.common.image.id }}
            imagePullPolicy: {{ .Values.common.image.pullPolicy }}
            command: ["/app/reset-cluster"]
            env:
            {{- $commonEnv := .Values.common.env | default dict }}
            {{- range $key, $value := $commonEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi 