apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "skyvault.fullname" . }}-binding
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "skyvault.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "skyvault.fullname" . }}
  apiGroup: rbac.authorization.k8s.io 