apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skyvault-rolebinding
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: skyvault-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: skyvault-role
  apiGroup: rbac.authorization.k8s.io 