apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "skyvault.fullname" . }}-pod-reader
  labels:
    {{- include "skyvault.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"] 