{{- range $key, $deployment := .Values.deployments }}
{{- if $deployment.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyvault-{{ $deployment.instanceName }}
  labels:
    {{- include "skyvault.labels" $ | nindent 4 }}
    app.kubernetes.io/component: skyvault
    app.kubernetes.io/instance-id: {{ $deployment.instanceName }}
spec:
  replicas: {{ $deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "skyvault.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: skyvault
      app.kubernetes.io/instance-id: {{ $deployment.instanceName }}
  template:
    metadata:
      labels:
        {{- include "skyvault.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: skyvault
        app.kubernetes.io/instance-id: {{ $deployment.instanceName }}
    spec:
      serviceAccountName: skyvault-serviceaccount
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.common.image.id }}"
          imagePullPolicy: {{ $.Values.common.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ $deployment.service.port }}
              protocol: TCP
          resources:
            {{- toYaml $deployment.resources | nindent 12 }}
          env:
            # Common environment variables
            {{- range $key, $value := $.Values.common.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            
            # Instance-specific environment variables
            {{- range $key, $value := $deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            
            - name: SKYVAULT_IMAGE_ID
              value: "{{ $.Values.common.image.id }}"

            - name: SKYVAULT_WORKER_SERVICE_ACCOUNT_NAME
              value: "skyvault-serviceaccount"
---
# Service for each Skyvault instance
apiVersion: v1
kind: Service
metadata:
  name: skyvault-{{ $deployment.instanceName }}
  labels:
    {{- include "skyvault.labels" $ | nindent 4 }}
    app.kubernetes.io/component: skyvault
    app.kubernetes.io/instance-id: {{ $deployment.instanceName }}
spec:
  type: {{ $deployment.service.type }}
  ports:
    - port: {{ $deployment.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if and (eq $deployment.service.type "NodePort") (hasKey $deployment.service "nodePort") }}
      nodePort: {{ $deployment.service.nodePort }}
      {{- end }}
  selector:
    {{- include "skyvault.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: skyvault
    app.kubernetes.io/instance-id: {{ $deployment.instanceName }}
{{- end }}
{{- end }} 