load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "skyvault_proto",
    srcs = ["skyvault/v1/skyvault.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@protobuf//:empty_proto",
    ],
)