name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - uses: Swatinem/rust-cache@v2
        
    - name: Install Protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler libprotobuf-dev --no-install-recommends
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        protoc --version

    - name: Run tests
      run: |
        export SQLX_OFFLINE=true
        RUST_BACKTRACE=1 cargo test -- --nocapture

  lint-helm:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Helm
      uses: azure/setup-helm@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run helm lint
      run: |
        helm lint charts/skyvault