name: Release

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read

  bump_scan_push:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    name: Bump Version, Scan, and Push
    permissions:
      contents: write
      packages: write
      security-events: write
    outputs:
      VERSION: ${{ steps.generate_version.outputs.VERSION }}
      COMMIT_HASH: ${{ steps.commit_and_push.outputs.COMMIT_HASH }}
      VERSION_NO_V: ${{ steps.generate_version.outputs.VERSION_NO_V }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for new commits
        id: check_commits
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -z "$LAST_TAG" ]; then
            echo "No previous tag found. Proceeding with version bump."
            echo "NEW_COMMITS=true" >> $GITHUB_ENV
            echo "LAST_VERSION=0.0.0" >> $GITHUB_ENV
          else
            NEW_COMMITS=$(git log $LAST_TAG..HEAD --oneline)
            if [ -z "$NEW_COMMITS" ]; then
              echo "❌ No new commits since last tag ($LAST_TAG)."
              echo "Cannot create a new release without new commits."
              echo "Please make some changes before running the release workflow."
              exit 1
            else
              echo "✅ New commits found since $LAST_TAG."
              echo "NEW_COMMITS=true" >> $GITHUB_ENV
              echo "LAST_VERSION=${LAST_TAG#v}" >> $GITHUB_ENV
            fi
          fi

      - name: Generate version
        id: generate_version
        run: |
          IFS='.' read -r major minor patch <<< "$LAST_VERSION"
          NEW_VERSION="$major.$minor.$((patch + 1))"
          echo "VERSION=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NO_V=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update manifests locally (no commit yet)
        env:
          NEW_TAGGED_VERSION: ${{ steps.generate_version.outputs.VERSION }}
        run: |
          VERSION_NO_V="${NEW_TAGGED_VERSION#v}"
          echo "New version (no v prefix): $VERSION_NO_V"
          echo "New version (with v prefix / tag): $NEW_TAGGED_VERSION"

          # Update charts/skyvault/Chart.yaml
          echo "Updating charts/skyvault/Chart.yaml to version $VERSION_NO_V"
          sed -i -e "s|^version:.*|version: $VERSION_NO_V|" \
                 -e "s|^appVersion:.*|appVersion: \"$VERSION_NO_V\"|" \
                 charts/skyvault/Chart.yaml

          # Update root Cargo.toml and Cargo.lock
          echo "Updating ./Cargo.toml and Cargo.lock to version $VERSION_NO_V"
          sed -i "3s/version = \".*\"/version = \"$VERSION_NO_V\"/" Cargo.toml
          sed -i '/name = "skyvault"/,/version = ".*"/ s/version = ".*"/version = "'$VERSION_NO_V'"/' Cargo.lock

          echo "Files updated locally, will commit after successful scan"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (early)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.release
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            skyvault:latest
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.generate_version.outputs.VERSION }}
          cache-from: |
            type=gha
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max

      - name: Scan Docker Image with Trivy
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: skyvault:latest
          format: "sarif"
          output: trivy-results.sarif
          exit-code: "1"
          ignore-unfixed: true
        continue-on-error: true

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Fail if vulnerabilities found
        if: steps.trivy_scan.outcome == 'failure'
        run: |
          echo "❌ Security vulnerabilities found in the image!"
          echo "Version bump will not be committed and image will not be pushed."
          exit 1

      - name: Commit version changes and push (only after successful scan)
        id: commit_and_push
        env:
          NEW_TAGGED_VERSION: ${{ steps.generate_version.outputs.VERSION }}
        run: |
          VERSION_NO_V="${NEW_TAGGED_VERSION#v}"
          
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Stage the updated files
          git add charts/skyvault/Chart.yaml
          git add Cargo.toml
          git add Cargo.lock

          # Commit changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: Bump version to $VERSION_NO_V"
            echo "✅ Committed version updates."
          else
            echo "No manifest changes to commit."
          fi

          # Tag this commit
          git tag "$NEW_TAGGED_VERSION"
          echo "✅ Tagged $NEW_TAGGED_VERSION"

          # Push commit and tag
          git push origin HEAD:${{ github.ref_name }}
          git push --tags

          echo "✅ Pushed commit and tag to ${{ github.ref_name }}."
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Push Docker image (reusing already built image)
        run: |
          echo "Pushing already built Docker images..."
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ steps.generate_version.outputs.VERSION }}

  create_release:
    runs-on: ubuntu-latest
    needs: [bump_scan_push]
    if: needs.bump_scan_push.outputs.VERSION != '' && success()
    name: Create Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump_scan_push.outputs.COMMIT_HASH }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        
      - name: Package Helm Chart
        run: |
          VERSION="${{ needs.bump_scan_push.outputs.VERSION }}"
          VERSION_NO_V="${VERSION#v}"
          helm package charts/skyvault --version $VERSION_NO_V --app-version $VERSION_NO_V

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.bump_scan_push.outputs.VERSION }}
          name: Release ${{ needs.bump_scan_push.outputs.VERSION }}
          generate_release_notes: true
          body: |
            ## Container Image
            ```
            ghcr.io/${{ github.repository }}:${{ needs.bump_scan_push.outputs.VERSION }}
            ```

            ## Artifacts
            - Container Image: `ghcr.io/${{ github.repository }}:${{ needs.bump_scan_push.outputs.VERSION }}`
            - Helm Chart: [skyvault-${{ needs.bump_scan_push.outputs.VERSION_NO_V }}.tgz](https://github.com/${{ github.repository }}/releases/download/${{ needs.bump_scan_push.outputs.VERSION }}/skyvault-${{ needs.bump_scan_push.outputs.VERSION_NO_V }}.tgz)
            
            ## Installation
            ```bash
            helm install my-release https://github.com/${{ github.repository }}/releases/download/${{ needs.bump_scan_push.outputs.VERSION }}/skyvault-${{ needs.bump_scan_push.outputs.VERSION_NO_V }}.tgz
            ```
          files: |
            skyvault-*.tgz
          
  purge_old_versions:
    runs-on: ubuntu-latest
    needs: bump_scan_push
    if: success()
    name: Purge Old Versions
    permissions:
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: skyvault-rs
          package-type: container
          num-old-versions-to-delete: 1
          min-versions-to-keep: 14
